### ISSUE TITLE
Pls Make this LIbrary available in bower 

### ISSUE THREAD

**Issue by JayKandari** [signalpoint/angular-drupal#5]
This is quite interesting library I found Angular + Drupal. I am developing an app, will raise an issue here if I find anything buggy. Grt module. Thanks.

**Comment by signalpoint** [comment]
@JayKandari I would love to make on Bower, except someone already took that name:

https://libraries.io/bower/angular-drupal

This is a bit strange, because their project name is `ngDrupal`, so one would expect that to be the Bower name, but that is not the case. I filed an issue with them a while back, but I still haven't heard anything from them:

https://github.com/alexpsi/ng-drupal/issues/1

I've considered contacting Bower to have the name released, but I haven't yet...

Thoughts?

**Comment by JayKandari** [comment]
Correct. When I previously downloaded angular-drupal from bower, It showed another author. I was surprised as why ngDrupal has come instead of angular-drupal. 
I too agree that this module should get the name 'angular-drupal'
I will also comment on the thread you mentioned.
