### ISSUE TITLE
$q is not a function at line 41

### ISSUE THREAD

**Issue by ashishsingh1331** [signalpoint/angular-drupal#6]
I am new to angularJS. I added code  in angular-drupal.js (image of code attached
![screenshot from 2015-08-18 14 17 46](https://cloud.githubusercontent.com/assets/5433986/9326036/7dda1232-45b4-11e5-8733-45760d1a26b3.png)
 )  to check username available to take or not. I am checking on blur of input field. It returns ok in my first call. As i blur again the same field it gives error "$q is not a function". 

![screenshot from 2015-08-18 14 14 13](https://cloud.githubusercontent.com/assets/5433986/9325930/b863f2d4-45b3-11e5-8515-d982ecf3362f.png)

I am confused something wrong with my code ?

![screenshot from 2015-08-18 14 24 59](https://cloud.githubusercontent.com/assets/5433986/9326130/3f67b9f4-45b5-11e5-9508-b48933ed3317.png)

**Comment by flemwad** [comment]
$q is a global service in angular that lets you handle promises, see: https://docs.angularjs.org/api/ng/service/$q. It looks to me like your error is saying it has no idea what $q is. This is likely because you're not injecting $q int your controller. via Function.$inject = ['$q'], or app.controller(MyController, ['$q', ... function ($q) {
}]);

See: https://docs.angularjs.org/api/auto/service/$injector

**Comment by ashishsingh1331** [comment]
Hi flemwad,
I was using angular.js 1.2.x version , as i upgraded to 1.4.5 it worked !!
